---
on:
  workflow_call:
    inputs:
      chart-path:
        type: string
        required: false
        default: chart

permissions: {}

jobs:
  chart-release:
    name: Chart Release
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Harden Runner
        if: github.event.repository.private == false
        id: harden_runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ github.sha }}

      - name: Set Up Crane
        id: setup_crane
        uses: ministryofjustice/action-setup-crane@b8d5be6affce54f6ff5f54e90174508bf4522672 # v1.0.0

      - name: Set Up Helm
        id: setup_helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Log in to GitHub Container Registry
        id: login_ghcr
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Chart
        id: package_chart
        shell: bash
        env:
          CHART_PATH: ${{ inputs.chart-path }}
        run: |
          helm package "${CHART_PATH}" --destination .helm-deploy

          CHART_NAME=$(yq -r '.name' "${CHART_PATH}/Chart.yaml")
          CHART_VERSION=$(yq -r '.version' "${CHART_PATH}/Chart.yaml")

          echo "chart_name=${CHART_NAME}" >> "${GITHUB_OUTPUT}"
          echo "chart_version=${CHART_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Push Chart
        id: push_chart
        shell: bash
        env:
          CHART_NAME: ${{ steps.package_chart.outputs.chart_name }}
          CHART_VERSION: ${{ steps.package_chart.outputs.chart_version }}
        run: |
          helm push ".helm-deploy/${CHART_NAME}-${CHART_VERSION}.tgz" oci://ghcr.io/ministryofjustice/data-platform-charts

          DIGEST=$(crane digest "ghcr.io/ministryofjustice/data-platform-charts/${CHART_NAME}:${CHART_VERSION}")
          echo "digest=${DIGEST}" >> "${GITHUB_OUTPUT}"

      - name: GitHub Build Provenance Attestation
        id: github_attestation
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-name: ghcr.io/ministryofjustice/data-platform-charts/${{ steps.package_chart.outputs.chart_name }}
          subject-digest: ${{ steps.push_chart.outputs.digest }}
          push-to-registry: true

      - name: GitHub Attestation Verification
        id: github_attestation_verification
        shell: bash
        env:
          CHART_NAME: ${{ steps.package_chart.outputs.chart_name }}
          GH_TOKEN: ${{ github.token }}
          CHART_VERSION: ${{ steps.package_chart.outputs.chart_version }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh attestation verify \
            "oci://ghcr.io/ministryofjustice/data-platform-charts/${CHART_NAME}:${CHART_VERSION}" \
            --repo "${REPOSITORY}" \
            --signer-workflow ministryofjustice/data-platform-github-actions/.github/workflows/chart-release.yml
