---
on:
  workflow_call:
    inputs:
      chart-path:
        type: string
        required: false
        default: chart

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        if: github.event.repository.private == false
        id: harden_runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set Up Helm
        id: setup_helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Set Up Helm Chart Testing
        id: setup_chart_testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Lint Chart
        id: lint_chart
        shell: bash
        env:
          CHART_PATH: ${{ inputs.chart-path }}
        run: |
          ct lint --charts "${CHART_PATH}"
