---
on:
  workflow_call:
    inputs:
      build-context:
        type: string
        required: false
        default: "."
      containerfile-path:
        type: string
        required: false
        default: "Containerfile"

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        if: github.event.repository.private == false
        id: harden_runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ inputs.build-context }}
          file: ${{ inputs.containerfile-path }}
          push: false
          tags: ${{ github.sha }}

      - name: Scan
        id: scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ github.sha }}
          severity-cutoff: high
          only-fixed: true
          output-format: sarif
          output-file: results.sarif

      - name: Upload SARIF
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: results.sarif
