---
on:
  workflow_call:
    inputs:
      build-context:
        type: string
        required: false
        default: "."
      clean-runner:
        type: boolean
        required: false
        default: false
      containerfile-path:
        type: string
        required: false
        default: "Containerfile"
      configuration-file:
        type: string
        required: false
        default: test/container-structure-test.yml

permissions: {}

jobs:
  container-test:
    name: Container Test
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        if: github.event.repository.private == false
        id: harden_runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Clean Runner
        if: inputs.clean-runner == true
        id: clean_runner
        uses: ministryofjustice/action-clean-runner@390530713a326ddc099b2114f38dd0f2f8eac6da # v1.1.0
        with:
          confirm: true

      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/action-setup-container-structure-test@d0636fa19d04c3fc71c30ae4eb8da03be63dbd4b # v1.0.0

      - name: Build
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ inputs.build-context }} # zizmor: ignore[template-injection]
          file: ${{ inputs.containerfile-path }}
          push: false
          tags: ${{ github.sha }}

      - name: Test
        id: test
        env:
          CONFIGURATION_FILE: ${{ inputs.configuration-file }}
          IMAGE_TAG: ${{ github.sha }}
        shell: bash
        run: |
          container-structure-test test --platform linux/arm64 --config "${CONFIGURATION_FILE}" --image "${IMAGE_TAG}"
