---
on:
  workflow_call:
    inputs:
      super-linter-variables:
        type: string
        required: false
        default: "{}"

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Harden Runner
        if: github.event.repository.private == false
        id: harden_runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Parse Super Linter Variables
        id: parse_super_linter_variables
        env:
          SUPER_LINTER_VARIABLES: ${{ inputs.super-linter-variables }}
        shell: bash
        run: |
          jq -r 'to_entries | .[] | "\(.key)=\(.value)"' <<< "${SUPER_LINTER_VARIABLES}" >>"${GITHUB_ENV}"

      - name: Super Linter
        id: super_linter
        uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: false
          # Disabling pull request summary comment until it's less noisy (tracked in super-linter issue #7458)
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          # Biome is very opinionated and enforces formatting rules that may conflict with other linters
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          # Terrascan is archived and will be removed in a future version of Super-Linter
          VALIDATE_TERRAFORM_TERRASCAN: false
          # Organisation stance is to remove Trivy
          VALIDATE_TRIVY: false
